# Generated by Django 6.0 on 2025-12-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='likes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
