# Generated by Django 6.0 on 2025-12-08 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_note_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='public',
            new_name='is_public',
        ),
    ]
